/* ============================================================
   LOCALIZATION — required by Playgama : the source language
   must come from bridge.platform.language.
   Default is ENGLISH. The language is switched to the player's
   own language ONLY when the real Playgama SDK is present
   (so a plain browser / GitHub Pages always shows English).
   ============================================================ */

const LANG = (() => {
  const SUPPORTED = ['en', 'fr', 'es', 'pt', 'de'];

  const STRINGS = {
    en: {
      'menu.play': 'PLAY',
      'menu.levels': 'LEVELS',
      'menu.shop': 'SHOP',
      'menu.best': 'BEST',
      'menu.tapStart': 'TAP TO START',
      'menu.daily': 'DAILY REWARD',
      'menu.dailyClaim': 'CLAIM!',
      'menu.dailyDone': 'CLAIMED — COME BACK TOMORROW!',
      'sound.on': '🔊',
      'sound.off': '🔇',
      'gameplay.hint': 'MOVE & MATCH THE COLORS!',
      'gameplay.perfect': 'PERFECT!',
      'gameplay.shield': 'SHIELD!',
      'gameplay.fever': 'FEVER!',
      'gameplay.level': 'LEVEL',
      'gameplay.objective.score': 'SCORE',
      'gameplay.objective.candies': 'CANDIES',
      'gameplay.objective.survive': 'SURVIVE',
      'loading.text': 'LOADING',
      'gameplay.combo': 'COMBO',
      'gameplay.pause': 'PAUSE',
      'gameplay.resume': 'RESUME',
      'gameplay.restart': 'RESTART',
      'gameplay.quit': 'QUIT',
      'gameover.title': 'GAME OVER',
      'gameover.newBest': 'NEW BEST!',
      'gameover.retry': 'RETRY',
      'gameover.revive': 'REVIVE',
      'gameover.menu': 'MENU',
      'gameover.score': 'SCORE',
      'gameover.best': 'BEST',
      'gameover.coins': 'COINS',
      'victory.title': 'LEVEL CLEAR!',
      'victory.next': 'NEXT',
      'victory.bonus': 'BONUS',
      'victory.coins': 'COINS',
      'levels.title': 'LEVELS',
      'levels.locked': 'LOCKED',
      'levels.home': 'HOME',
      'shop.title': 'SWEET SHOP',
      'shop.coins': 'COINS',
      'shop.buy': 'BUY',
      'shop.owned': 'OWNED',
      'shop.watch': 'WATCH',
      'shop.equip': 'EQUIP',
      'shop.equipped': 'EQUIPPED',
      'shop.back': 'BACK',
      'shop.notEnough': 'NOT ENOUGH COINS!',
      'shop.videoSection': 'UNLOCK WITH A VIDEO',
      'shop.heartPlus': 'Heart +1',
      'shop.doublePoints': 'Double Points',
      'shop.magnet': 'Candy Magnet',
      'shop.shield': 'Sugar Shield',
      'shop.skinRainbow': 'Rainbow Ball',
      'shop.skinGold': 'Golden Ball',
      'shop.skinNeon': 'Neon Ball',
      'shop.faceHappy': 'Happy Face',
      'shop.faceCool': 'Cool Face',
      'shop.faceLove': 'Love Face',
      'shop.trailConfetti': 'Confetti Trail',
      'shop.trailStar': 'Star Trail',
      'shop.trailBubble': 'Bubble Trail',
      'shop.gateStriped': 'Striped Gates',
      'shop.gateSparkle': 'Sparkle Gates',
      'shop.gateDots': 'Dotted Gates'
    },
    fr: {
      'menu.play': 'JOUER',
      'menu.levels': 'NIVEAUX',
      'menu.shop': 'BOUTIQUE',
      'menu.best': 'RECORD',
      'menu.tapStart': 'TAPE POUR JOUER',
      'menu.daily': 'RÉCOMPENSE QUOTIDIENNE',
      'menu.dailyClaim': 'RÉCUPÉRER !',
      'menu.dailyDone': 'RÉCUPÉRÉE — REVIENS DEMAIN !',
      'sound.on': '🔊',
      'sound.off': '🔇',
      'gameplay.hint': 'DÉPLACE-TOI ET ASSOCIE LES COULEURS !',
      'gameplay.perfect': 'PARFAIT !',
      'gameplay.shield': 'BOUCLIER !',
      'gameplay.fever': 'FÉVRIE !',
      'gameplay.level': 'NIVEAU',
      'gameplay.objective.score': 'SCORE',
      'gameplay.objective.candies': 'BONBONS',
      'gameplay.objective.survive': 'SURVIVRE',
      'loading.text': 'CHARGEMENT',
      'gameplay.combo': 'COMBO',
      'gameplay.pause': 'PAUSE',
      'gameplay.resume': 'REPRENDRE',
      'gameplay.restart': 'RECOMMENCER',
      'gameplay.quit': 'QUITTER',
      'gameover.title': 'PARTIE TERMINÉE',
      'gameover.newBest': 'NOUVEAU RECORD !',
      'gameover.retry': 'REJOUER',
      'gameover.revive': 'CONTINUER',
      'gameover.menu': 'MENU',
      'gameover.score': 'SCORE',
      'gameover.best': 'RECORD',
      'gameover.coins': 'BONBONS',
      'victory.title': 'NIVEAU RÉUSSI !',
      'victory.next': 'SUIVANT',
      'victory.bonus': 'BONUS',
      'victory.coins': 'BONBONS',
      'levels.title': 'NIVEAUX',
      'levels.locked': 'VERROUILLÉ',
      'levels.home': 'ACCUEIL',
      'shop.title': 'BOUTIQUE DE BONBONS',
      'shop.coins': 'BONBONS',
      'shop.buy': 'ACHETER',
      'shop.owned': 'POSSÉDÉ',
      'shop.watch': 'REGARDER',
      'shop.equip': 'ÉQUIPER',
      'shop.equipped': 'ÉQUIPÉ',
      'shop.back': 'RETOUR',
      'shop.notEnough': 'PAS ASSEZ DE BONBONS !',
      'shop.videoSection': 'DÉBLOQUE AVEC UNE VIDÉO',
      'shop.heartPlus': 'Cœur +1',
      'shop.doublePoints': 'Points Doubles',
      'shop.magnet': 'Aimant à Bonbons',
      'shop.shield': 'Bouclier Sucré',
      'shop.skinRainbow': 'Balle Arc-en-ciel',
      'shop.skinGold': 'Balle Dorée',
      'shop.skinNeon': 'Balle Néon',
      'shop.faceHappy': 'Visage Heureux',
      'shop.faceCool': 'Visage Cool',
      'shop.faceLove': 'Visage Amoureux',
      'shop.trailConfetti': 'Traînée de Confettis',
      'shop.trailStar': 'Traînée d’Étoiles',
      'shop.trailBubble': 'Traînée de Bulles',
      'shop.gateStriped': 'Portes Rayées',
      'shop.gateSparkle': 'Portes Scintillantes',
      'shop.gateDots': 'Portes à Pois'
    },
    es: {
      'menu.play': 'JUGAR',
      'menu.shop': 'TIENDA',
      'menu.best': 'RÉCORD',
      'menu.tapStart': 'TOCA PARA JUGAR',
      'gameplay.hint': '¡MUÉVETE Y COINCIDE LOS COLORES!',
      'gameplay.perfect': '¡PERFECTO!',
      'gameplay.shield': '¡ESCUDO!',
      'loading.text': 'CARGANDO',
      'gameplay.combo': 'COMBO',
      'gameplay.pause': 'PAUSA',
      'gameplay.resume': 'CONTINUAR',
      'gameplay.restart': 'REINICIAR',
      'gameplay.quit': 'SALIR',
      'gameover.title': 'FIN DEL JUEGO',
      'gameover.newBest': '¡NUEVO RÉCORD!',
      'gameover.retry': 'REINTENTAR',
      'gameover.revive': 'REVIVIR',
      'gameover.menu': 'MENÚ',
      'gameover.score': 'PUNTOS',
      'gameover.best': 'RÉCORD',
      'gameover.coins': 'DULCES',
      'shop.title': 'TIENDA DE DULCES',
      'shop.coins': 'DULCES',
      'shop.buy': 'COMPRAR',
      'shop.owned': 'COMPRADO',
      'shop.back': 'VOLVER',
      'shop.notEnough': '¡NO HAY SUFICIENTES DULCES!',
      'shop.heartPlus': 'Corazón +1',
      'shop.doublePoints': 'Puntos Dobles',
      'shop.magnet': 'Imán de Dulces',
      'shop.shield': 'Escudo de Azúcar',
      'menu.levels': 'NIVELES',
      'menu.daily': 'RECOMPENSA DIARIA',
      'menu.dailyClaim': '¡RECOGER!',
      'menu.dailyDone': '¡RECOGIDA — VUELVE MAÑANA!',
      'gameplay.fever': '¡FIEBRE!',
      'gameplay.level': 'NIVEL',
      'gameplay.objective.score': 'PUNTOS',
      'gameplay.objective.candies': 'DULCES',
      'gameplay.objective.survive': 'SOBREVIVIR',
      'victory.title': '¡NIVEL SUPERADO!',
      'victory.next': 'SIGUIENTE',
      'victory.bonus': 'BONUS',
      'victory.coins': 'DULCES',
      'levels.title': 'NIVELES',
      'levels.locked': 'BLOQUEADO',
      'levels.home': 'INICIO',
      'shop.watch': 'VER',
      'shop.equip': 'EQUIPAR',
      'shop.equipped': 'EQUIPADO',
      'shop.videoSection': 'DESBLOQUEA CON UN VIDEO',
      'shop.skinRainbow': 'Bola Arcoíris',
      'shop.skinGold': 'Bola Dorada',
      'shop.skinNeon': 'Bola Neón',
      'shop.faceHappy': 'Cara Feliz',
      'shop.faceCool': 'Cara Guay',
      'shop.faceLove': 'Cara Enamorada',
      'shop.trailConfetti': 'Estela de Confeti',
      'shop.trailStar': 'Estela de Estrellas',
      'shop.trailBubble': 'Estela de Burbujas',
      'shop.gateStriped': 'Puertas Rayadas',
      'shop.gateSparkle': 'Puertas Brillantes',
      'shop.gateDots': 'Puertas de Lunares'
    },
    pt: {
      'menu.play': 'JOGAR',
      'menu.shop': 'LOJA',
      'menu.best': 'RECORDE',
      'menu.tapStart': 'TOQUE PARA JOGAR',
      'gameplay.hint': 'MOVA-SE E COMBINE AS CORES!',
      'gameplay.perfect': 'PERFEITO!',
      'gameplay.shield': 'ESCUDO!',
      'loading.text': 'CARREGANDO',
      'gameplay.combo': 'COMBO',
      'gameplay.pause': 'PAUSA',
      'gameplay.resume': 'CONTINUAR',
      'gameplay.restart': 'REINICIAR',
      'gameplay.quit': 'SAIR',
      'gameover.title': 'FIM DE JOGO',
      'gameover.newBest': 'NOVO RECORDE!',
      'gameover.retry': 'TENTAR DE NOVO',
      'gameover.revive': 'REVIVER',
      'gameover.menu': 'MENU',
      'gameover.score': 'PONTOS',
      'gameover.best': 'RECORDE',
      'gameover.coins': 'DOCES',
      'shop.title': 'LOJA DE DOCES',
      'shop.coins': 'DOCES',
      'shop.buy': 'COMPRAR',
      'shop.owned': 'COMPRADO',
      'shop.back': 'VOLTAR',
      'shop.notEnough': 'DOCES INSUFICIENTES!',
      'shop.heartPlus': 'Coração +1',
      'shop.doublePoints': 'Pontos Dobrados',
      'shop.magnet': 'Ímã de Doces',
      'shop.shield': 'Escudo de Açúcar',
      'menu.levels': 'NÍVEIS',
      'menu.daily': 'RECOMPENSA DIÁRIA',
      'menu.dailyClaim': 'PEGAR!',
      'menu.dailyDone': 'PEGO — VOLTE AMANHÃ!',
      'gameplay.fever': 'FEBRE!',
      'gameplay.level': 'NÍVEL',
      'gameplay.objective.score': 'PONTOS',
      'gameplay.objective.candies': 'DOCES',
      'gameplay.objective.survive': 'SOBREVIVER',
      'victory.title': 'NÍVEL CONCLUÍDO!',
      'victory.next': 'PRÓXIMO',
      'victory.bonus': 'BÔNUS',
      'victory.coins': 'DOCES',
      'levels.title': 'NÍVEIS',
      'levels.locked': 'BLOQUEADO',
      'levels.home': 'INÍCIO',
      'shop.watch': 'VER',
      'shop.equip': 'EQUIPAR',
      'shop.equipped': 'EQUIPADO',
      'shop.videoSection': 'DESBLOQUEIE COM UM VÍDEO',
      'shop.skinRainbow': 'Bola Arco-Íris',
      'shop.skinGold': 'Bola Dourada',
      'shop.skinNeon': 'Bola Neon',
      'shop.faceHappy': 'Rosto Feliz',
      'shop.faceCool': 'Rosto Legal',
      'shop.faceLove': 'Rosto Apaixonado',
      'shop.trailConfetti': 'Rastro de Confete',
      'shop.trailStar': 'Rastro de Estrelas',
      'shop.trailBubble': 'Rastro de Bolhas',
      'shop.gateStriped': 'Portões Listrados',
      'shop.gateSparkle': 'Portões Brilhantes',
      'shop.gateDots': 'Portões com Bolinhas'
    },
    de: {
      'menu.play': 'SPIELEN',
      'menu.shop': 'SHOP',
      'menu.best': 'REKORD',
      'menu.tapStart': 'TIPPEN ZUM STARTEN',
      'gameplay.hint': 'BEWEGE DICH UND TREFFE DIE FARBEN!',
      'gameplay.perfect': 'PERFEKT!',
      'gameplay.shield': 'SCHILD!',
      'loading.text': 'LÄDT',
      'gameplay.combo': 'COMBO',
      'gameplay.pause': 'PAUSE',
      'gameplay.resume': 'WEITER',
      'gameplay.restart': 'NEUSTART',
      'gameplay.quit': 'BEENDEN',
      'gameover.title': 'SPIEL VORBEI',
      'gameover.newBest': 'NEUER REKORD!',
      'gameover.retry': 'NOCHMAL',
      'gameover.revive': 'WEITERSPIELEN',
      'gameover.menu': 'MENÜ',
      'gameover.score': 'PUNKTE',
      'gameover.best': 'REKORD',
      'gameover.coins': 'SÜSSIGKEITEN',
      'shop.title': 'SÜSSIGKEITEN-SHOP',
      'shop.coins': 'SÜSSIGKEITEN',
      'shop.buy': 'KAUFEN',
      'shop.owned': 'GEKAUFT',
      'shop.back': 'ZURÜCK',
      'shop.notEnough': 'NICHT GENUG SÜSSIGKEITEN!',
      'shop.heartPlus': 'Herz +1',
      'shop.doublePoints': 'Doppelte Punkte',
      'shop.magnet': 'Süßigkeiten-Magnet',
      'shop.shield': 'Zucker-Schild',
      'menu.levels': 'LEVELS',
      'menu.daily': 'TAGESBELOHNUNG',
      'menu.dailyClaim': 'ABHOLEN!',
      'menu.dailyDone': 'ABGEHOLT — KOMM MORGEN WIEDER!',
      'gameplay.fever': 'FIEBER!',
      'gameplay.level': 'LEVEL',
      'gameplay.objective.score': 'PUNKTE',
      'gameplay.objective.candies': 'SÜSSIGKEITEN',
      'gameplay.objective.survive': 'ÜBERLEBEN',
      'victory.title': 'LEVEL GESCHAFFT!',
      'victory.next': 'WEITER',
      'victory.bonus': 'BONUS',
      'victory.coins': 'SÜSSIGKEITEN',
      'levels.title': 'LEVELS',
      'levels.locked': 'GESPERRT',
      'levels.home': 'START',
      'shop.watch': 'ANSEHEN',
      'shop.equip': 'AUSRÜSTEN',
      'shop.equipped': 'AUSGERÜSTET',
      'shop.videoSection': 'MIT VIDEO FREISCHALTEN',
      'shop.skinRainbow': 'Regenbogen-Ball',
      'shop.skinGold': 'Goldener Ball',
      'shop.skinNeon': 'Neon-Ball',
      'shop.faceHappy': 'Glückliches Gesicht',
      'shop.faceCool': 'Cooles Gesicht',
      'shop.faceLove': 'Verliebtes Gesicht',
      'shop.trailConfetti': 'Konfetti-Spur',
      'shop.trailStar': 'Sternen-Spur',
      'shop.trailBubble': 'Blasen-Spur',
      'shop.gateStriped': 'Gestreifte Tore',
      'shop.gateSparkle': 'Funkelnde Tore',
      'shop.gateDots': 'Gepunktete Tore'
    }
  };

  function detect() {
    let lang = 'en';
    try {
      // Only the real Playgama SDK decides the language.
      // Without it the game stays in English (default).
      if (Bridge.available) {
        const raw = Bridge.platform.language;
        if (SUPPORTED.indexOf(raw) !== -1) lang = raw;
      }
    } catch (e) { /* noop */ }
    return lang;
  }

  let current = detect();

  return {
    get current() { return current; },
    t(key) {
      const table = STRINGS[current] || STRINGS.en;
      return table[key] || STRINGS.en[key] || key;
    }
  };
})();
